---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# GitOps Kustomization for Brisa Cubana Clean Intelligence
# This file defines the declarative infrastructure state
# Flux CD reconciles this every 5 minutes

metadata:
  name: brisa-production
  namespace: brisa-system

resources:
  # Applications
  - apps/api-deployment.yaml
  - apps/web-deployment.yaml

  # Services
  - services/api-service.yaml
  - services/web-service.yaml

  # Ingress and routing
  - ingress/main-ingress.yaml

  # ConfigMaps and Secrets
  - config/app-config.yaml

  # HPA (Horizontal Pod Autoscaler)
  - autoscaling/api-hpa.yaml
  - autoscaling/web-hpa.yaml

  # Service Mesh
  - mesh/virtual-services.yaml
  - mesh/destination-rules.yaml

commonLabels:
  app.kubernetes.io/name: brisa-cubana
  app.kubernetes.io/managed-by: flux
  environment: production

namespace: brisa-production

images:
  # API container image
  - name: ghcr.io/albertodimas/brisa-api
    newTag: latest

  # Web container image
  - name: ghcr.io/albertodimas/brisa-web
    newTag: latest

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - ENABLE_OBSERVABILITY=true
      - ENABLE_CHAOS_ENGINEERING=false

secretGenerator:
  - name: app-secrets
    envs:
      - secrets.env

replicas:
  - name: api-deployment
    count: 3
  - name: web-deployment
    count: 2
