version: 2
updates:
  # Enable version updates for npm (pnpm workspaces)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "albertodimas"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "eslint*"
          - "prettier"
          - "vitest"
          - "@playwright/*"
      development-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "eslint*"
          - "prettier"
          - "vitest"
          - "@playwright/*"
          - "@testing-library/*"

  # Web app (Next.js)
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "albertodimas"
    labels:
      - "dependencies"
      - "web"
    commit-message:
      prefix: "chore(deps/web)"

  # API (Hono)
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "albertodimas"
    labels:
      - "dependencies"
      - "api"
    commit-message:
      prefix: "chore(deps/api)"

  # UI Package
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "albertodimas"
    labels:
      - "dependencies"
      - "ui"
    commit-message:
      prefix: "chore(deps/ui)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "albertodimas"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(deps/ci)"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "albertodimas"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps/docker)"

  # Python (MkDocs documentation)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "albertodimas"
    labels:
      - "dependencies"
      - "documentation"
    commit-message:
      prefix: "chore(deps/docs)"
