site_name: Brisa Cubana Clean Intelligence Docs
site_description: Documentación oficial de la plataforma de limpieza inteligente para Miami-Dade.
site_author: Brisa Cubana Team
repo_url: https://github.com/albertodimas/brisa-cubana-clean-intelligence
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 Brisa Cubana Clean Intelligence

# Navigation
nav:
  - Home: index.md

  - Para desarrolladores:
      - Panorama general: for-developers/README.md
      - Quickstart (5 minutos): for-developers/quickstart.md
      - Variables de entorno: for-developers/environment-variables.md
      - Plan de entregas y releases: development/delivery-plan.md
      - Workflow de testing local: development/local-testing-workflow.md
      - Inventario Diátaxis: development/diataxis-mapping.md
      - Estándares de documentación: development/documentation-standards.md
      - KPIs & métricas: development/kpi-dashboard.md
      - Referencia de API: for-developers/api-reference.md
      - Guía de testing: for-developers/testing.md
      - Guía de despliegue: for-developers/deployment.md
      - Configuración Railway: for-developers/railway-env-setup.md
      - Modo API fake: for-developers/fake-api-mode.md
      - Runbook de producción: for-developers/production-runbook.md
      - Secretos GitHub: for-developers/github-secrets.md
      - Configuración staging: for-developers/staging-setup.md
      - Arquitectura:
          - Arquitectura general: for-developers/architecture.md
          - Índice de diagramas: for-developers/diagrams/README.md
          - C4 Contexto: for-developers/diagrams/c4-context-2025Q4.md
          - C4 Contenedores: for-developers/diagrams/c4-containers-2025Q4.md
          - Flujo de reservas: for-developers/diagrams/booking-flow-r1.md
          - Panel cliente: for-developers/diagrams/panel-cliente-r2.md
          - App staff: for-developers/diagrams/app-staff-r3.md
          - Secuencia CleanScore: for-developers/diagrams/cleanscore-sequence.md
      - Tutoriales:
          - CleanScore™: for-developers/tutorials/cleanscore-tutorial.md
          - Concierge AI: for-developers/tutorials/concierge-ai-tutorial.md
      - Roadmaps técnicos:
          - Observabilidad (Fase 2): for-developers/observability-phase2.md
          - Advanced Features (Fase 3): for-developers/phase3-advanced-features.md
          - Enterprise Grade (Fase 4): for-developers/phase4-enterprise-grade.md
          - Procedimientos de rollback: for-developers/rollback-procedures.md
      - Design system: for-developers/design-system/index.md
      - IA & ML:
          - Panorama general: for-developers/ai-ml/model-cards/README.md
          - Concierge MVP: for-developers/ai-ml/model-cards/model/concierge-mvp-v0.1.md
          - CleanScore v0.1: for-developers/ai-ml/model-cards/model/cleanscore-v0.1.md
      - Guía Copilot: for-developers/copilot/index.md
      - Operaciones técnicas:
          - Checklist de despliegue: operations/production/DEPLOYMENT_CHECKLIST.md
          - Guía de despliegue: operations/production/PRODUCTION_DEPLOYMENT_GUIDE.md
          - Preparación para producción: operations/production/PRODUCTION_READINESS_REPORT.md
          - Auditoría de producción: operations/production/PRODUCTION_AUDIT_REPORT.md
          - Configuración de secretos: operations/production/DEPLOYMENT_SETUP.md
          - Guía Railway: operations/production/RAILWAY_FIX.md
      - Runbooks:
          - Índice: operations/runbooks/README.md
          - Operational Readiness Review: operations/runbooks/OPERATIONAL_READINESS_REVIEW.md
          - Go-Live: operations/runbooks/GO_LIVE.md
          - Rollback: operations/runbooks/ROLLBACK.md
          - Incident Response: operations/runbooks/INCIDENT_RESPONSE.md

  - Negocio y operaciones:
      - Panorama general: for-business/README.md
      - Visión y estrategia: for-business/vision-strategy.md
      - Mercado y cumplimiento: for-business/market-compliance.md
      - Experiencia de usuario: for-business/user-experience.md
      - Stack tecnológico: for-business/tech-stack.md
      - IA y automatización: for-business/ai-automation.md
      - Integraciones: for-business/integrations.md
      - Roadmap: for-business/roadmap.md
      - Checklist pre-rollout: for-business/checklist-pre-rollout.md
      - Operaciones:
          - Panorama general: for-business/operations/index.md
          - Dominio y branding: for-business/operations/domain-and-branding.md
          - Plan de entrevistas: for-business/operations/interview-plan.md
          - Plan Sprint 0: for-business/operations/sprint0-plan.md
          - Resumen pre-dev: for-business/operations/pre-dev-summary.md
          - Resumen pre-dev (Ejecutivo): for-business/operations/pre-dev-summary-executive.md
          - Políticas:
              - Panorama general: for-business/operations/policies/index.md
              - Política de privacidad (borrador): for-business/operations/policies/privacy-policy-draft.md
              - Carta de gobierno IA: for-business/operations/policies/governance-ia-charter.md
          - SOPs:
              - Panorama general: for-business/operations/sops/index.md
              - Onboarding Staff: for-business/operations/sops/onboarding-staff.md
              - Gestión de inventario: for-business/operations/sops/inventory-management.md
              - Respuesta a emergencias: for-business/operations/sops/emergency-response.md
              - Simulacro de emergencias: for-business/operations/sops/emergency-response-tabletop.md
              - Mantenimiento de equipos: for-business/operations/sops/maintenance.md
          - Branding: for-business/operations/branding/style-guide-outline.md
          - Finanzas: for-business/operations/finance/financial-model-outline.md
          - Checklists:
              - Panorama general: for-business/operations/checklists/index.md
              - Sprint 0: for-business/operations/checklists/sprint0-checklist.md
              - Lanzamiento: for-business/operations/checklists/launch-checklist.md
          - Marketing: for-business/operations/marketing/gtm-plan.md
          - QA: for-business/operations/qa/testing-strategy.md
          - Riesgos: for-business/operations/risk/risk-register.md
          - Datos: for-business/operations/data/data-analytics-plan.md
          - Soporte: for-business/operations/support/support-playbook.md
          - Partners: for-business/operations/partners/partner-onboarding.md
          - Producto:
              - Roadmap de producto: for-business/operations/product/product-roadmap.md
              - Plan MVP Lean: for-business/operations/product/mvp-lean-plan.md
              - Caso de uso - María: for-business/operations/product/caso-uso-maria.md
              - Caso de uso - Carlos: for-business/operations/product/caso-uso-carlos.md
          - Integraciones: for-business/operations/integrations/sandbox-plan.md
          - Registro de decisiones: for-business/operations/decision-log/decisions.md
      - Datos de mercado:
          - Índice: for-business/market-data/index.md
          - Turismo 2024: for-business/market-data/tourism-2024-records.md
          - Datos salariales: for-business/market-data/wage-maids-miami.md
          - Competencia: for-business/market-data/cleaning-competition-snapshot.md
      - Insights: for-business/insights/index.md

  - Guías:
      - Panorama general: guides/README.md

  - Referencia:
      - Panorama general: reference/README.md
      - Fuentes: reference/sources.md
      - Plantillas:
          - Panorama general: reference/templates/index.md
          - Plantilla ADR: reference/templates/adr-template.md
          - Plantilla Model Card: reference/templates/model-card-template.md
          - Plantilla notas de entrevista: reference/templates/interview-notes-template.md
          - Acta de reunión: reference/templates/meeting-minutes-template.md
          - Evaluación modelos IA: reference/templates/ia-model-eval-template.md
          - Contrato de emergencia: reference/templates/emergency-contract-template.md
          - Manual de estimaciones: reference/templates/estimation-manual-template.md
          - Manual CleanScore: reference/templates/cleanscore-manual-template.md
          - Checklist seguros: reference/templates/insurance-checklist.md
          - Guía seguridad químicos: reference/templates/chemical-safety-guideline.md
          - Checklist integración CRM: reference/templates/crm-integration-checklist.md
          - Ejemplos:
              - Contrato ejemplo (Carlos): reference/templates/examples/emergency-contract-sample-carlos.md
              - Estimación ejemplo (María): reference/templates/examples/estimation-manual-sample-maria.md

  - Registro de cambios:
      - Índice general: changelog/index.md
      - Sesión 2025-10-01 · Workflow de testing local: changelog/session-2025-10-01-local-testing-workflow.md
      - Sesión 2025-10-01 · Auditoría de seguridad: changelog/session-2025-10-01-security-audit.md
      - Sesión 2025-10-02 · Auditoría y optimización: changelog/session-2025-10-02-audit-and-optimization.md
      - Sesión 2025-10-02 · Optimización del repositorio: changelog/session-2025-10-02-repository-optimization.md

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.follow
  palette:
    # Light mode
    - scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: es
  icon:
    repo: fontawesome/brands/github
    logo: material/broom

# Markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

# Plugins
plugins:
  - search:
      lang:
        - es
        - en
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
      locale: es
      fallback_to_build_date: true
      strict: false
  - minify:
      minify_html: true

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extra JavaScript
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/albertodimas/brisa-cubana-clean-intelligence
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com
    - icon: fontawesome/brands/instagram
      link: https://instagram.com
  version:
    provider: mike
    default: latest
  analytics:
    provider: google
    property: G-XXXXXXXXXX # Replace with actual GA4 ID
  generator: false

# Extra configuration
strict: false # Set to true in CI to catch broken links
