site_name: Brisa Cubana Clean Intelligence Docs
site_description: Documentación oficial de la plataforma de limpieza inteligente.
site_author: Brisa Cubana Team
repo_url: https://github.com/tu-usuario/brisa-cubana-clean-intelligence
nav:
  - Inicio: index.md
  - 01 · Visión y Estrategia: 01-vision-estrategia.md
  - 02 · Mercado y Compliance: 02-mercado-y-compliance.md
  - 03 · Experiencia y Diseño: 03-experiencia-y-diseno.md
  - 04 · Arquitectura y Stack: 04-arquitectura-y-stack.md
  - 05 · IA y Automatización: 05-ia-y-automatizacion.md
  - 06 · Integraciones y Ecosistema: 06-integraciones-ecosistema.md
  - 07 · Roadmap y Operaciones: 07-roadmap-y-operaciones.md
  - Checklist Pre-Rollout: checklist-pre-rollout.md
  - Insights de Investigación: insights/index.md
  - 08 · Operaciones y Ejecución:
      - Overview: operations/index.md
      - Dominio & Branding: operations/domain-and-branding.md
      - Entrevistas de validación: operations/interview-plan.md
      - Plan Sprint 0: operations/sprint0-plan.md
      - Integraciones & Sandbox: operations/integrations/sandbox-plan.md
      - Políticas y Gobernanza:
          - Resumen: operations/policies/index.md
          - Política de privacidad (borrador): operations/policies/privacy-policy-draft.md
          - Carta de gobernanza IA: operations/policies/governance-ia-charter.md
      - SOPs operativos:
          - Resumen: operations/sops/index.md
          - Onboarding staff: operations/sops/onboarding-staff.md
          - Gestión inventario: operations/sops/inventory-management.md
          - Emergencias climáticas: operations/sops/emergency-response.md
          - Simulacro tabletop crisis: operations/sops/emergency-response-tabletop.md
          - Mantenimiento equipos: operations/sops/maintenance.md
      - Branding: operations/branding/style-guide-outline.md
      - Modelo financiero: operations/finance/financial-model-outline.md
      - Checklists:
          - Resumen: operations/checklists/index.md
          - Sprint 0: operations/checklists/sprint0-checklist.md
          - Lanzamiento: operations/checklists/launch-checklist.md
      - Plan marketing & GTM: operations/marketing/gtm-plan.md
      - Testing & QA: operations/qa/testing-strategy.md
      - Risk register: operations/risk/risk-register.md
      - Plan de datos: operations/data/data-analytics-plan.md
      - Playbook soporte: operations/support/support-playbook.md
      - Partner onboarding: operations/partners/partner-onboarding.md
      - Roadmap producto: operations/product/product-roadmap.md
      - Plan MVP Lean: operations/product/mvp-lean-plan.md
      - Caso de uso (María): operations/product/caso-uso-maria.md
      - Caso de uso (Carlos): operations/product/caso-uso-carlos.md
      - Decision log: operations/decision-log/decisions.md
      - Resumen ejecutivo expansión: operations/pre-dev-summary-executive.md
      - Resumen pre-desarrollo: operations/pre-dev-summary.md
  - 09 · Plantillas y utilidades:
      - Entrevista: resources/templates/interview-notes-template.md
      - Minuta de reunión: resources/templates/meeting-minutes-template.md
      - ADR: resources/templates/adr-template.md
      - Evaluación de modelo IA: resources/templates/ia-model-eval-template.md
      - Model card: resources/templates/model-card-template.md
      - Contrato emergencia B2B: resources/templates/emergency-contract-template.md
      - Estimación manual premium: resources/templates/estimation-manual-template.md
      - CleanScore asistido (MVP): resources/templates/cleanscore-manual-template.md
      - Ejemplos contratos & estimaciones:
          - Contrato — Carlos: resources/templates/examples/emergency-contract-sample-carlos.md
          - Estimación — María: resources/templates/examples/estimation-manual-sample-maria.md
      - Checklist seguros: resources/templates/insurance-checklist.md
      - Guía seguridad química: resources/templates/chemical-safety-guideline.md
      - Checklist CRM: resources/templates/crm-integration-checklist.md
      - Datos mercado 2024:
          - Turismo 2024: resources/market/tourism-2024-records.md
          - Salarios limpieza: resources/market/wage-maids-miami.md
          - Competencia local: resources/market/cleaning-competition-snapshot.md
  - 10 · Anexos y registros:
      - Artefactos arquitectura:
          - Overview: resources/architecture/README.md
          - C4 contexto: resources/architecture/c4-context-2025Q4.md
          - C4 contenedores: resources/architecture/c4-containers-2025Q4.md
          - Booking flow R1: resources/architecture/booking-flow-r1.md
          - Panel cliente R2: resources/architecture/panel-cliente-r2.md
          - App staff R3: resources/architecture/app-staff-r3.md
          - CleanScore secuencia: resources/architecture/cleanscore-sequence.md
      - Model cards IA:
          - Overview: ai/model-cards/README.md
          - Concierge MVP v0.1: ai/model-cards/model/concierge-mvp-v0.1.md
          - CleanScore v0.1: ai/model-cards/model/cleanscore-v0.1.md
      - Changelog: changelog/index.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - navigation.instant
  palette:
    - scheme: default
      primary: teal
      accent: pink
    - scheme: slate
      primary: teal
      accent: pink
  language: es
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com
