# Railway Configuration
# This file configures Railway to use the Dockerfile for building the API service

[build]
builder = "dockerfile"
dockerfilePath = "apps/api/Dockerfile"

[deploy]
startCommand = "node apps/api/dist/server.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
