[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
restartPolicyType = "on_failure"

[services.api]
root = "apps/api"
[services.api.env]
NODE_ENV = "production"
PORT = "3001"

[services.api.nixpacks]
install = ["pnpm install --frozen-lockfile --filter @brisa/api" ]
build = ["pnpm --filter @brisa/api build"]
start = ["pnpm --filter @brisa/api start"]

[services.web]
root = "apps/web"
[services.web.env]
NODE_ENV = "production"

[services.web.nixpacks]
install = ["pnpm install --frozen-lockfile --filter @brisa/web"]
build = ["pnpm --filter @brisa/web build"]
start = ["pnpm --filter @brisa/web start"]
