---
# Chaos Mesh Pod Failure Experiment
# Randomly kills pods to test resilience and auto-recovery

apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: api-pod-failure
  namespace: brisa-production
spec:
  action: pod-failure
  mode: one  # Kill one pod at a time
  duration: "30s"
  selector:
    namespaces:
      - brisa-production
    labelSelectors:
      app: api
      version: stable
  scheduler:
    cron: "@every 2h"  # Run every 2 hours
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: api-pod-kill
  namespace: brisa-production
spec:
  action: pod-kill
  mode: fixed-percent
  value: "30"  # Kill 30% of pods
  duration: "10s"
  selector:
    namespaces:
      - brisa-production
    labelSelectors:
      app: api
  scheduler:
    cron: "0 3 * * 6"  # Saturday 3 AM (low traffic)
