name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs toolchain
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation
        run: mkdocs build --strict

      - name: Configure git credentials
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Deploy with mike
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(date +"%Y.%m.%d")
          mike deploy --push --update-aliases "$VERSION" latest
          mike set-default --push latest

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
