name: Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "packages/**"
      - ".github/workflows/deploy-production.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: production-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter=@brisa/api db:generate

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test

      - name: Build web app
        run: cd apps/web && pnpm build
        env:
          NEXT_PUBLIC_API_URL: https://api.brisacubana.com
          NEXT_PUBLIC_APP_URL: https://brisacubana.com

  deploy-api:
    name: Deploy API to Railway
    needs: lint-and-test
    if: ${{ secrets.RAILWAY_PRODUCTION_TOKEN != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: production
      url: https://api.brisacubana.com

    steps:
      - name: Check Railway secret
        run: |
          if [ -z "${{ secrets.RAILWAY_PRODUCTION_TOKEN }}" ]; then
            echo "⚠️  Skipping deploy-api: missing RAILWAY_PRODUCTION_TOKEN secret"
            echo "Please configure the RAILWAY_PRODUCTION_TOKEN secret in GitHub repository settings"
            exit 1
          fi
          echo "✅ Railway token configured, proceeding with deployment"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}
        run: railway up --service api-production --detach

      - name: Wait for deployment
        run: sleep 45

      - name: Health check
        run: |
          max_attempts=5
          attempt=0
          while [ $attempt -lt $max_attempts ]; do
            response=$(curl -s -o /dev/null -w "%{http_code}" https://api.brisacubana.com/health)
            if [ $response -eq 200 ]; then
              echo "Health check passed"
              exit 0
            fi
            attempt=$((attempt + 1))
            echo "Health check attempt $attempt/$max_attempts failed with status $response"
            sleep 10
          done
          echo "Health check failed after $max_attempts attempts"
          exit 1

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "✅ API deployed to production successfully",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *API Production Deployment Successful*\n\n*Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>by ${{ github.actor }}\n*Branch:* `${{ github.ref_name }}`\n*URL:* https://api.brisacubana.com"
                  }
                }
              ]
            }

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "❌ API production deployment failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ *API Production Deployment Failed*\n\n*Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}> by ${{ github.actor }}\n*Branch:* `${{ github.ref_name }}`\n*Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
                  }
                }
              ]
            }

  deploy-web:
    name: Deploy Web to Vercel
    needs: lint-and-test
    if: ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production
      url: https://brisacubana.com

    steps:
      - name: Check Vercel secrets
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ] || [ -z "${{ secrets.VERCEL_ORG_ID }}" ] || [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "⚠️  Skipping deploy-web: missing Vercel secrets"
            echo "Required secrets: VERCEL_TOKEN, VERCEL_ORG_ID, VERCEL_PROJECT_ID"
            echo "Please configure these secrets in GitHub repository settings"
            exit 1
          fi
          echo "✅ Vercel secrets configured, proceeding with deployment"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web app
        run: cd apps/web && pnpm build
        env:
          NEXT_PUBLIC_API_URL: https://api.brisacubana.com
          NEXT_PUBLIC_APP_URL: https://brisacubana.com

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "✅ Web app deployed to production successfully",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ *Web App Production Deployment Successful*\n\n*Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}> by ${{ github.actor }}\n*Branch:* `${{ github.ref_name }}`\n*URL:* https://brisacubana.com"
                  }
                }
              ]
            }

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "❌ Web app production deployment failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ *Web App Production Deployment Failed*\n\n*Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}> by ${{ github.actor }}\n*Branch:* `${{ github.ref_name }}`\n*Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
                  }
                }
              ]
            }
