name: Payments Reconcile

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reconcile:
    runs-on: ubuntu-latest

    # PostgreSQL service for testing reconciliation
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: brisa_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/brisa_test
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm --filter=@brisa/api db:generate

      - name: Create database schema
        run: pnpm --filter=@brisa/api db:push --skip-generate --accept-data-loss

      - name: Reconcile payments with Stripe
        run: pnpm --filter=@brisa/api payments:reconcile
