name: Post-Deploy Seed

on:
  workflow_run:
    workflows:
      - CI (Main Branch)
    types:
      - completed

concurrency:
  group: post-deploy-seed-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  seed-production:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment:
      name: production-api
    steps:
      - name: Validate production database secret
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [ -z "$DATABASE_URL" ]; then
            echo "::error::Set the DATABASE_URL secret in the production-api environment to enable automatic seeding."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          repository: ${{ github.event.workflow_run.head_repository.full_name }}

      - name: Setup project
        uses: ./.github/actions/setup-project
        with:
          install-playwright: false
          run-prisma-generate: true
          database-url: ${{ secrets.DATABASE_URL }}
          database-url-unpooled: ${{ secrets.DATABASE_URL_UNPOOLED }}
          api-token: ${{ secrets.API_TOKEN }}
          jwt-secret: ${{ secrets.JWT_SECRET }}
          auth-secret: ${{ secrets.AUTH_SECRET }}
          log_drain_verification_code: ${{ secrets.LOG_DRAIN_VERIFICATION_CODE }}

      - name: Apply Prisma migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED }}
        run: |
          ./scripts/prisma-deploy-or-baseline.sh

      - name: Seed production data (operativo)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_URL_UNPOOLED: ${{ secrets.DATABASE_URL_UNPOOLED }}
        run: |
          export DATABASE_URL_UNPOOLED="${DATABASE_URL_UNPOOLED:-$DATABASE_URL}"
          pnpm --filter @brisa/api db:seed:operativo
