name: PR Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: "Rama o tag a validar (por defecto main)"
        required: false
        default: "main"

jobs:
  smoke-tests:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    uses: ./.github/workflows/project-pipeline.yml
    with:
      job-name: PR smoke tests
      run-secret-scan: true
      run-database-prep: true
      run-e2e-suite: smoke
      playwright-report-name: playwright-report-smoke
      upload-playwright-only-on-failure: true
      next-public-posthog-key: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
      next-public-posthog-host: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
    secrets:
      api-token: ${{ secrets.API_TOKEN }}
      jwt-secret: ${{ secrets.JWT_SECRET }}
      auth-secret: ${{ secrets.AUTH_SECRET }}
      portal-magic-link-from: ${{ secrets.PORTAL_MAGIC_LINK_FROM }}
      portal-magic-link-smtp-host: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_HOST }}
      portal-magic-link-smtp-port: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_PORT }}
      portal-magic-link-smtp-user: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_USER }}
      portal-magic-link-smtp-password: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_PASSWORD }}
      portal-magic-link-smtp-secure: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_SECURE }}
      log_drain_verification_code: ${{ secrets.LOG_DRAIN_VERIFICATION_CODE }}
      e2e_admin_email: ${{ secrets.E2E_ADMIN_EMAIL }}
      e2e_admin_password: ${{ secrets.E2E_ADMIN_PASSWORD }}
      e2e_coordinator_email: ${{ secrets.E2E_COORDINATOR_EMAIL }}
      e2e_coordinator_password: ${{ secrets.E2E_COORDINATOR_PASSWORD }}

  smoke-tests-manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/project-pipeline.yml
    with:
      job-name: PR smoke tests (manual)
      run-secret-scan: true
      run-database-prep: true
      run-e2e-suite: smoke
      playwright-report-name: playwright-report-smoke
      upload-playwright-only-on-failure: true
      checkout-ref: ${{ inputs.ref }}
      next-public-posthog-key: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
      next-public-posthog-host: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
    secrets:
      api-token: ${{ secrets.API_TOKEN }}
      jwt-secret: ${{ secrets.JWT_SECRET }}
      auth-secret: ${{ secrets.AUTH_SECRET }}
      portal-magic-link-from: ${{ secrets.PORTAL_MAGIC_LINK_FROM }}
      portal-magic-link-smtp-host: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_HOST }}
      portal-magic-link-smtp-port: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_PORT }}
      portal-magic-link-smtp-user: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_USER }}
      portal-magic-link-smtp-password: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_PASSWORD }}
      portal-magic-link-smtp-secure: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_SECURE }}
      log_drain_verification_code: ${{ secrets.LOG_DRAIN_VERIFICATION_CODE }}
      e2e_admin_email: ${{ secrets.E2E_ADMIN_EMAIL }}
      e2e_admin_password: ${{ secrets.E2E_ADMIN_PASSWORD }}
      e2e_coordinator_email: ${{ secrets.E2E_COORDINATOR_EMAIL }}
      e2e_coordinator_password: ${{ secrets.E2E_COORDINATOR_PASSWORD }}
