name: PR Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: "Rama o tag a validar (por defecto main)"
        required: false
        default: "main"

jobs:
  smoke-tests:
    uses: ./.github/workflows/project-pipeline.yml
    secrets: inherit
    with:
      environment-name: preview-web
      job-name: ${{ github.event_name == 'workflow_dispatch' && 'PR smoke tests (manual)' || 'PR smoke tests' }}
      checkout-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || '' }}
      run-secret-scan: true
      run-database-prep: true
      run-e2e-suite: smoke
      playwright-report-name: playwright-report-smoke
      upload-playwright-only-on-failure: true
