name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  smoke-tests:
    uses: ./.github/workflows/project-pipeline.yml
    with:
      job-name: PR smoke tests
      run-secret-scan: true
      run-database-prep: true
      run-e2e-suite: smoke
      playwright-report-name: playwright-report-smoke
      upload-playwright-only-on-failure: true
      e2e-admin-email: ${{ secrets.E2E_ADMIN_EMAIL }}
      e2e-admin-password: ${{ secrets.E2E_ADMIN_PASSWORD }}
      e2e-coordinator-email: ${{ secrets.E2E_COORDINATOR_EMAIL }}
      e2e-coordinator-password: ${{ secrets.E2E_COORDINATOR_PASSWORD }}
    secrets:
      api-token: ${{ secrets.API_TOKEN }}
      jwt-secret: ${{ secrets.JWT_SECRET }}
      auth-secret: ${{ secrets.AUTH_SECRET }}
      portal-magic-link-from: ${{ secrets.PORTAL_MAGIC_LINK_FROM }}
      portal-magic-link-smtp-host: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_HOST }}
      portal-magic-link-smtp-port: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_PORT }}
      portal-magic-link-smtp-user: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_USER }}
      portal-magic-link-smtp-password: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_PASSWORD }}
      portal-magic-link-smtp-secure: ${{ secrets.PORTAL_MAGIC_LINK_SMTP_SECURE }}
